# tap "homebrew/bundle"
# tap "homebrew/cask-fonts"
# tap "homebrew/cask-versions"
tap "hashicorp/tap"

brew "awscli"
brew "awsume"
brew "gh"
brew "go@1.22"
brew "jq"
brew "mysql-client"
brew "nodenv"
brew "pyenv"
brew "starship"
brew "terraform"
brew "tokei"
brew "tree"

cask "1password"
cask "alfred"
cask "appcleaner"
cask "deepl"
cask "font-fira-code-nerd-font"
cask "font-sauce-code-pro-nerd-font"
cask "rectangle"
# cask "karabiner-elements" MacOSのバグが直ったら
# cask "raycast"
# cask "skitch"
cask "tableplus"
# cask "warp"

# Self Serviceでインストールしたけどその前にbrewでインストールしたから
# これを消すとApplicationsフォルダーを消しに行こうとするから残す
cask "docker"
# cask "google-japanese-ime"
cask "visual-studio-code"
cask "zoom"
cask "notion"
