tap "hashicorp/tap"

brew "awscli"
brew "awsume"
brew "gh"
brew "go@1.22"
brew "jq"
brew "mysql-client"
brew "nodenv"
brew "pyenv"
brew "starship"
brew "terraform"
brew "tokei"
brew "tree"

cask "1password"
cask "alfred"
cask "appcleaner"
cask "deepl"
# cask "docker" 毎回インスールしようとするため
cask "font-fira-code-nerd-font"
cask "font-sauce-code-pro-nerd-font"
cask "ghostty"
cask "notion"
cask "rectangle"
# cask "karabiner-elements" MacOSのバグが直ったら
cask "tableplus"
cask "visual-studio-code"
cask "zoom"
